version: '3'


secrets:
  pgpassword:
    file: ./postgres/pgpassword


services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432"] 

  redis:
    image: "redis:alpine"
    restart: always

  postgres:
    image: postgres:alpine
    volumes:
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
    secrets:
      - pgpassword
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgpassword
    restart: always